spring:
  application:
    name: 'service-discovery'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: ${SERVER_PORT:8761}
