spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://brunolessamaxx28:rS1oDcvbkHZTxoFC@clusterhelpdesk.49ouwoh.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service API'
    description: 'Component responsible for managing user data.'
    version: '1.0.0'
    contact:
      name: 'Bruno Lessa'
      email: 'brunolessamaxx28@gmail.com'

