spring:
  application:
    name: 'bff'
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    connection-timeout: 10000
  cloud:
    config:
      uri: 'config-server'
springdoc:
  openapi:
    title: 'BFF API'
    description: 'Component responsible for aggregating the microservices and exposing a single endpoint.'
    version: '1.0.0'
    contact:
      name: 'Bruno Lessa'
      email: 'brunolessamaxx28@gmail.com'
eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
