spring:
  application:
    name: 'order-service-api'
  cloud:
    config:
      uri: 'config-server'
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    connection-timeout: 10000
    template:
      exchange: 'helpdesk'
      routing-key: 'rk.orders.create'
