spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
          default-label: master
          username: ${CONFIG_REPO_USERNAME}
          password: ${CONFIG_REPO_PASSWORD}
server:
  port: ${SERVER_PORT:8888}
eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
